Repository bellshade/wpu_bot, pull requests merged in 2022-03, with the labels that each got.

#52 Feat: Sticker emergency meeting dan sedikit aman
  data/sticker.json
Labels: enhancement, stickers

#53 add: majikayo
  data/sticker.json
Labels: enhancement, stickers

#54 feat: Menambah Sticker hmm_kuduga
  data/sticker.json
Labels: enhancement, stickers

#55 feat: Menambahkan Sticker Baru
  data/sticker.json
Labels: enhancement

#56 feat: Menambahkan Sticker Baru
  data/sticker.json
Labels: enhancement

#57 add: new sticker
  data/sticker.json
Labels: enhancement, stickers

#58 feat: add sticker info
  commands/sticker-list.command.js
  commands/sticker.command.js
  events/interactionCreate.event.js
  package-lock.json
  package.json
Labels: enhancement

#60 feat: Menambahkan Sticker Baru
  data/sticker.json
Labels: enhancement

#48 feat: add reason to point system
  modules/point-system.js
  modules/utility.js
Labels: enhancement

#61 fix: fields value to long on roleinfo
  commands/roleinfo.command.js
Labels: bug

#62 feat: add slash command permissions
  commands/avatar.command.js
  commands/channelInfo.command.js
  commands/ping.command.js
  commands/roleinfo.command.js
  commands/servericon.command.js
  commands/serverinfo.command.js
  commands/sticker-list.command.js
  commands/sticker.command.js
  commands/userinfo.command.js
  deploy-commands.js
  package.json
  remove-commands.js
Labels: enhancement

#66 feat: update deploy workflows
  .github/workflows/deploy.yml
Labels: enhancement

#65 feat: add timeout command
  commands/timeout.command.js
  modules/utility.js
Labels: enhancement

#67 fix: deployCommands
  deploy-commands.js
  events/ready.event.js
  modules/deployCommands.js
Labels: bug

#68 fix: command permissions deployment
  .github/workflows/deploy.yml
  modules/deployCommands.js
Labels: bug

#69 fix: change ready behaviour
  events/ready.event.js
  modules/deployCommands.js
  modules/pointAutomation.js
Labels: bug

#70 fix: typo
  commands/avatar.command.js
  commands/channelInfo.command.js
  commands/ping.command.js
  commands/roleinfo.command.js
  commands/servericon.command.js
  commands/serverinfo.command.js
  commands/sticker-list.command.js
  commands/sticker.command.js
  commands/timeout.command.js
  commands/userinfo.command.js
  modules/deployCommands.js
Labels: bug

#71 fix: add missing params and remove choice
  commands/timeout.command.js
Labels: bug
