Repository bellshade/wpu_bot, pull requests merged in 2022-01, with the labels that each got.

#5 feat: eslint
  .eslintrc.json
  .github/workflows/ci-pr.yml
  .mergify.yml
  index.js
  modules/filters.js
  modules/public.js
  modules/stickers.js
  modules/timeout.js
  modules/utility.js
  package-lock.json
  package.json
Labels: enhancement

#6 feat: add analytics modules
  .env.example
  README.md
  index.js
  modules/analytics.js
  package-lock.json
  package.json
  prisma/migrations/20220106082509_initial/migration.sql
  prisma/migrations/20220106083141_update_perkenalan/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
Labels: enhancement

#7 feat: refactor timeout modules
  modules/timeout.js
  modules/utility.js
Labels: enhancement

#9 feat: add module perkenalan
  .env.example
  .gitignore
  assets/fonts/BebasNeue-Regular.ttf
  assets/fonts/OFL.txt
  assets/images/welcome.png
  index.js
  modules/analytics.js
  modules/perkenalan.js
  modules/utility.js
  package-lock.json
  package.json
Labels: enhancement

#10 feat: update mergify
  .mergify.yml
Labels: enhancement

#11 fix: timeout days
  modules/timeout.js
  modules/utility.js
Labels: bug, core: ready to merge

#12 feat: add module info
  .eslintrc.json
  index.js
  modules/info.js
  modules/utility.js
Labels: enhancement

#13 feat: info interaction commands
  .env.example
  .eslintrc.json
  commands/avatar.command.js
  commands/channelInfo.command.js
  commands/ping.command.js
  commands/roleinfo.command.js
  commands/servericon.command.js
  commands/serverinfo.command.js
  commands/userinfo.command.js
  deploy-commands.js
  events/guildMemberAdd.event.js
  events/interactionCreate.event.js
  events/messageCreate.event.js
  events/ready.event.js
  index.js
  package-lock.json
  package.json
Labels: enhancement

#14 fix: getUserFromID from utility.js
  modules/info.js
  modules/timeout.js
  modules/utility.js
Labels: Ok to merge, bug

#15 feat: add pointSystem modules
  .env.example
  commands/channelInfo.command.js
  commands/userinfo.command.js
  events/messageCreate.event.js
  events/ready.event.js
  modules/point-system.js
  package-lock.json
  package.json
  prisma/migrations/20220113142919_point_system/migration.sql
  prisma/schema.prisma
Labels: enhancement

#16 fix: perkenalan
  .eslintrc.json
  .gitignore
  commands/channelInfo.command.js
  commands/roleinfo.command.js
  commands/servericon.command.js
  commands/serverinfo.command.js
  commands/userinfo.command.js
  events/guildMemberAdd.event.js
  events/messageCreate.event.js
  events/ready.event.js
  index.js
  modules/info.js
  modules/perkenalan.js
  modules/point-system.js
  modules/timeout.js
  modules/utility.js
Labels: bug

#17 fix: fix highest role
  commands/userinfo.command.js
  data/filters.json
  modules/info.js
Labels: bug

#18 fix: stickers modules & delete filters modules
  data/filters.json
  data/sticker.json
  events/messageCreate.event.js
  modules/filters.js
  modules/stickers.js
Labels: bug

#20 fix: commands handler and refactor
  events/ready.event.js
  modules/info.js
  modules/point-system.js
  modules/utility.js
Labels: bug

#22 feat: update sticker module
  .env.example
  data/sticker.json
  events/messageCreate.event.js
  index.js
  modules/point-system.js
  modules/stickers.js
Labels: enhancement

#26 fix: propperly use message referance for stickers
  modules/stickers.js
Labels: bug

#31 feat: menambahkan algoritma baru
  data/sticker.json
Labels: enhancement

#32 feat: add or decrease point for multiple user
  modules/point-system.js
Labels: enhancement

#33 Feat: Sticker Iwak
  data/sticker.json
Labels: enhancement

#35 feat: reorder data json
  data/sticker.json
Labels: enhancement

#37 feat: add new sticker
  data/sticker.json
Labels: ready-to-merge, enhancement, stickers, sudah di review!

#38 feat: Menambahkan Sticker Baru
  data/sticker.json
Labels: ready-to-merge, enhancement, sudah di review!

#39 feat: add cd
  .github/workflows/deploy.yml
Labels: enhancement

#40 feat: Menambahkan Sticker Baru
  data/sticker.json
Labels: enhancement

#42 feat: Menambahkan Sticker Baru
  data/sticker.json
Labels: enhancement

#44 feat: Stiker Baru (#41)
  data/sticker.json
Labels: enhancement

#45 feat: save point change history
  modules/point-system.js
  prisma/migrations/20220122095845_add_point_history/migration.sql
  prisma/schema.prisma
Labels: ready-to-merge, enhancement, sudah di review!

#46 feat: nambahin stiker (#42)
  data/sticker.json
Labels: enhancement

#47 feat: nambahin stiker (#43)
  data/sticker.json
Labels: enhancement
